### ISSUE TITLE
Downloading error over 5.6 KB data and Streaming data upto 5.6 KB

### ISSUE THREAD

**Issue by OmnixOne** [G6EJD/G6EJD-ESP-File-Server#1]
Hello everyone,

I want to download and stream files of spiffs using a web server but I'm struggling when it comes to downloading and streaming files over 5.6 KB.
While using this library here I get the size of maxLen and it is 5.6 KB, I think due to the maxLen size I can't download files over 5.6 KB, and on-stream it streams only 5.6 KB of data. So how do I download and stream data over 5.6 KB? and how can I change maxLen size?
Device: M5Core 2

**Comment by G6EJD** [comment]
What ESP32 compiler are you using, if not 1.0.6, try that.
Or change to a chunked response, see server readme

**Comment by OmnixOne** [comment]
I am using ESP32 1.0.6 version.

**Comment by OmnixOne** [comment]
And I have tried all chunked responses, but the bug still continues and
it's downloading and streaming data up to 5KB only.

**Comment by G6EJD** [comment]
Which board/cpu are you using, how much spare RAM is available?
I think is is most likely a compiler setting or board selection issue as it was all working and the library has not been updated in over 3-years, so it must be something other than the asynchronous web-server

**Comment by OmnixOne** [comment]
**Full Board Description**
Microcontroller: Tensilica 32-bit Single-/Dual-core CPU Xtensa LX6

[ESP32 BoardLink](https://grobotronics.com/esp32-development-board-devkit-v1.html)

Arduino IDE  1.8.19
Compiler 
Xtensa GNU compiler collection (GCC)
Version:  Tensilica 32-bit Single-/Dual-core CPU Xtensa LX6
ESPAsyncWebServer library branch == f71e3d427b5be9791a8a2c93cf8079792c3a9a26 (We are using this latest master branch)
 Log File of uploading, downloading and streaming:
```
/home/omnixone05/Music/ESPAsynch_Server_v1/ESPAsynch_Server_v1.ino
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.1.106, MASK: 255.255.255.0, GW: 192.168.1.1
IP Address: 192.168.1.106
System started successfully...
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 1 - SCAN_DONE
Uploading file...
Transferred : 1460 Bytes
Transferred : 1268 Bytes
Transferred : 1460 Bytes
Transferred : 1412 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1460 Bytes
Transferred : 1412 Bytes
Transferred : 1460 Bytes
Transferred : 1412 Bytes
Transferred : 1436 Bytes
Transferred : 1460 Bytes
Transferred : 1412 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1460 Bytes
Transferred : 1412 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1434 Bytes
Transferred : 1 Bytes
Transferred : 1 Bytes
Transferred : 1436 Bytes
Transferred : 1434 Bytes
Transferred : 1 Bytes
Transferred : 1 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1460 Bytes
Transferred : 1412 Bytes
Transferred : 1436 Bytes
Transferred : 1436 Bytes
Transferred : 1428 Bytes
File Directory...
Streaming file...
Stream handler started...
[W][AsyncTCP.cpp:969] _poll(): rx timeout 4
Downloading file...
Download handler started...
[W][AsyncTCP.cpp:969] _poll(): rx timeout 4
```

Here I am attaching the screenshot of arduino setting.
![Screenshot from 2022-06-14 12-05-54](https://user-images.githubusercontent.com/96113852/173511399-aaaf6a54-ccc1-4903-b87d-5a27dcac7d5d.png)
And please tell how we can increase the size of maxLen ?? because the size of maxLen is 5.6 KB and it downloading and straming upto 5.6 KB only.

**Comment by G6EJD** [comment]
Sorry. That’s a query for the library author at Espressif, not me.

**Comment by OmnixOne** [comment]
Have you tried to download and stream a File above 5.6 KB?

**Comment by G6EJD** [comment]
Not since I published the code, I may try it it again when I can find time. I'll let you know when I do. It all worked up to 1MB files, that's why I included the test files.

**Comment by OmnixOne** [comment]
We will wait for you.

**Comment by elektroboard** [comment]
me too

**Comment by G6EJD** [comment]
If you use an earlier compiler version 1.6 for the ESP32 then it will work

**Comment by franzbischoff** [comment]
This solves the problem on download requests:

```cpp
    if (request->url().startsWith("/downloadhandler"))
    {
      Serial.println("Download handler started...");
      MessageLine = "";
      File file = FS.open(filename, "r");
      String contentType = getContentType("download");
      AsyncWebServerResponse *response = request->beginResponse(contentType, file.size(), [file](uint8_t *buffer, size_t maxLen, size_t total) mutable ->  size_t
                                                                { return file.read(buffer, maxLen); });
      response->addHeader("Server", "ESP Async Web Server");
      request->send(response);
    }
```

**Comment by elektroboard** [comment]
> This solves the problem on download requests:
> 
> ```c++
>     if (request->url().startsWith("/downloadhandler"))
>     {
>       Serial.println("Download handler started...");
>       MessageLine = "";
>       File file = FS.open(filename, "r");
>       String contentType = getContentType("download");
>       AsyncWebServerResponse *response = request->beginResponse(contentType, file.size(), [file](uint8_t *buffer, size_t maxLen, size_t total) mutable ->  size_t
>                                                                 { return file.read(buffer, maxLen); });
>       response->addHeader("Server", "ESP Async Web Server");
>       request->send(response);
>     }
> ```

Thanks. İ will try it

**Comment by wsndy** [comment]
> > This solves the problem on download requests:
> > ```
> >     if (request->url().startsWith("/downloadhandler"))
> >     {
> >       Serial.println("Download handler started...");
> >       MessageLine = "";
> >       File file = FS.open(filename, "r");
> >       String contentType = getContentType("download");
> >       AsyncWebServerResponse *response = request->beginResponse(contentType, file.size(), [file](uint8_t *buffer, size_t maxLen, size_t total) mutable ->  size_t
> >                                                                 { return file.read(buffer, maxLen); });
> >       response->addHeader("Server", "ESP Async Web Server");
> >       request->send(response);
> >     }
> > ```
> 
> Thanks. İ will try it

Hi, is your problem solved? I had the same problem, still only able to download 5.6k with the new code.
Arduino IDE 1.8.19
ESP32 compiler version 2.0.5 
board: DOIT ESP32 DEVKIT V1

**Comment by franzbischoff** [comment]
It solved it for me. Maybe you should review the current version of this library and see what works for you: https://github.com/me-no-dev/ESPAsyncWebServer
BR

**Comment by ELECTRONICA-EL-AVION** [comment]
Saludos!!!
Quiero descargar los archivos subidos o cargados a mi ESP32 S3, pero no deja descargar a mas de 5.6Kb, utilizando arduino 1.8.19.
Han probado descargar los archivos a mas de 5.6Kb, tambien he utilizado el ESP32 WROOM y tampoco el mismo problema de descarga ya he actualizado los archivos y nada.

**Comment by G6EJD** [comment]
He actualizado el código para corregir este problema. es realmente un problema del compilador, no un problema de código.

**Comment by ayaghini** [comment]
Dear David,

First, thanks for your time here.

Another user with the same problem here.

I am using ESP32-S3, also I am trying to use the SD instead of the SPIFF. I can successfully download files up to 5.6k but no luck with the greater ones. This is the change I made to make it compatible with SD:

```
if (request->url().startsWith("/downloadhandler")) {
      Serial.println("Download handler started...");
      MessageLine = "";
      File file = SD.open(filename);
      String contentType = getContentType("download");
      AsyncWebServerResponse* response = request->beginResponse(contentType, file.size(), [file](uint8_t *buffer, size_t maxLen, size_t total) mutable -> size_t {
        return file.read(buffer, maxLen);
      });
      response->addHeader("Server", "ESP Async Web Server");
      request->send(response);
      downloadtime = millis() - start;
      downloadsize = GetFileSize(filename);
      request->redirect("/dir");
    }
```

I know that this is perhaps not your priority, but any help that puts me in the right direction would be appreciated. 

Thanks

PS: I am using wifi in AP mode.

I tried the solution proposed earlier, removing those lines will cause the board to crash constantly.

**Comment by ayaghini** [comment]
> This solves the problem on download requests:
> 
> ```c++
>     if (request->url().startsWith("/downloadhandler"))
>     {
>       Serial.println("Download handler started...");
>       MessageLine = "";
>       File file = FS.open(filename, "r");
>       String contentType = getContentType("download");
>       AsyncWebServerResponse *response = request->beginResponse(contentType, file.size(), [file](uint8_t *buffer, size_t maxLen, size_t total) mutable ->  size_t
>                                                                 { return file.read(buffer, maxLen); });
>       response->addHeader("Server", "ESP Async Web Server");
>       request->send(response);
>     }
> ```

This at the end solved my problem. For anyone else, my issue was my ESP board  (Adafruit ESP32-S3) that crashed when I did upload the sketch.

Thanks Dave for this great work!

**Comment by G6EJD** [comment]
Thank you I have updated the code accordingly.
