### ISSUE TITLE
Download/delete page crashes when more than dozen files exist

### ISSUE THREAD

**Issue by ayaghini** [G6EJD/G6EJD-ESP-File-Server#3]
Hello,

calling Download/delete page crashes when there are many files.  I have close to 100 files and when I click on the download button on the web-interface, ESP restarts.

ESP32-S3
using with SD card and SD library.
`fileinfo Filenames[200];  // Enough for most purposes!`

Status page shows that I have 217KB free RAM.

If this is not a bug, a Solution could be to divide download page into group of only 50 or 20 files perhaps, but I don't know where to start and do that.

Thanks,
Ali

**Comment by G6EJD** [comment]
I think your expecting too much from the ESP32 as it’s not a PC!
The amount of RAM at runtime will be a lot less too. 
I have fixed the code for the download limit, so are you sure you’re using the latest code in detail?
Actually the problem is with the Asynchronous WebServer library big this code.

**Comment by ayaghini** [comment]
Thanks for the reply. Agreed, that is why I am suggesting pagination. This is a great work you have done, it added a long-time missing feature and I am just suggesting improvement. My knowledge of HTML is very poor but I am trying to learn how to add this and I hope someone else here sees that and can help.

I did more dive and realized it is not the number of files but the file name themselves so I am using very smaller names but some one can hit the limit soon. 

I am using the latest code, but I will download the code again and double check.

Again, thanks for your great work.

**Comment by ayaghini** [comment]
Here is a quick update, definitely having too many files with long name will cause the server to crash. 

This is what I did: 
- Limit number of files both in the directory() and in numFiles[] array to 80
- reduce my naming to base minimum (less than 8 character)

**Comment by G6EJD** [comment]
The Arduino / ESP implementation only supports 8.3 file naming, so that was an issue now solved and file numbers is a function of runtime memory that soon gets used when a file is being buffered during transfers.

**Comment by ayaghini** [comment]
Thanks Dave,

I can see that you have edited ver1 and not 1.1, was that intentional?

**Comment by G6EJD** [comment]
Thanks, I’ll check and amend accordingly.

**Comment by G6EJD** [comment]
I'd already updated v1.1, so all changes made, thank you.
