### ISSUE TITLE
Code does't work for Download or Steam

### ISSUE THREAD

**Issue by blueokanna** [G6EJD/G6EJD-ESP-File-Server#4]
Hello there, I just use the code and whether STA mode or AP mode if I upload the file to ESP32, but it can't download(It locks on 5.55KB) or stream the whole text(HTTP1.1/302 Connection Close). I am not sure what happened there and I hope it will update! Many thanks.

**Comment by cacs200281** [comment]
Hello,
Same problem here :(

**Comment by blueokanna** [comment]
I probably wanna say that the author may not focus on here🌚

**Comment by G6EJD** [comment]
The Asynchronous Web Server Source code has to be modified to get this to work. Details in the G6EJD repository.

**Comment by blueokanna** [comment]
> The Asynchronous Web Server Source code has to be modified to get this to work. Details in the G6EJD repository. 

Thanks for your project! I Will read it later and to learn the code👏

**Comment by cacs200281** [comment]
> The Asynchronous Web Server Source code has to be modified to get this to work. Details in the G6EJD repository.

Hey, 
Thanks a lot for share your knowledge! I'll search that info ;)
Cheers

**Comment by cacs200281** [comment]
> > The Asynchronous Web Server Source code has to be modified to get this to work. Details in the G6EJD repository.
> 
> Hey, Thanks a lot for share your knowledge! I'll search that info ;) Cheers

4 hours searching the solution without success, I will give up for today because may be this task must be done by a guy that has more experience than me.

**Comment by G6EJD** [comment]
To get the uploader to work with large files, you need to change line 320 in the Async library in file WebResponses.cpp to:  outLen = sprintf((char*)buf+headLen, "%04x", readLen) + headLen;.
The original formatter was %x and then used spaces to fill. This will format it with leading zeros up to 4 places.

**Comment by blueokanna** [comment]
> To get the uploader to work with large files, you need to change line 320 in the Async library in file WebResponses.cpp to:  outLen = sprintf((char*)buf+headLen, "%04x", readLen) + headLen;.
> The original formatter was %x and then used spaces to fill. This will format it with leading zeros up to 4 places. 

looks perfect

**Comment by cacs200281** [comment]
I just did a test and the upload issue was solved :) but the download still freezing at 5.6k

**Comment by G6EJD** [comment]
I don’t see the download issue. What is the file type?

**Comment by blueokanna** [comment]
> I just did a test and the upload issue was solved :) but the download still freezing at 5.6k

Me too it still the same problem for me, Download still doesn't work

**Comment by cacs200281** [comment]
Hello Dave, 
I am testing with a *.txt file, when the file has a size up to 5.54Kb(seen by windows explorer) the download runs like a charm.
If the file has a size > 5.54Kb the download is freezing when the browser(chrome and edge) shows 5.6Kb.
Thank you very much for your help.

Kind regards

**Comment by cacs200281** [comment]
> I don’t see the download issue. What is the file type?

Hello Dave, 
I am testing with a *.txt file, when the file has a size up to 5.54Kb(seen by windows explorer) the download runs like a charm.
If the file has a size > 5.54Kb the download is freezing when the browser(chrome and edge) shows 5.6Kb.
Thank you very much for your help.

Kind regards

**Comment by G6EJD** [comment]
It seems like another Asynchronous WebServer library issue, I presume you have tried another browser and what happens when you stream the same file does it lock up, it could well be a browser issue too.

**Comment by cacs200281** [comment]
> It seems like another Asynchronous WebServer library issue, I presume you have tried another browser and what happens when you stream the same file does it lock up, it could well be a browser issue too.

In my PC I tried by Chrome and Edge, I also tried in my cell phone(Chrome), all attempts with no success yet.

**Comment by cacs200281** [comment]
> > I just did a test and the upload issue was solved :) but the download still freezing at 5.6k
> 
> Me too it still the same problem for me, Download still doesn't work

hey,
what about your attempts?

**Comment by cacs200281** [comment]
this is an image from my browser(Chrome) when trying to download a file:

![error](https://github.com/G6EJD/G6EJD-ESP-File-Server/assets/36003206/311309b4-0740-4ef8-8221-5cae124e3261)

**Comment by blueokanna** [comment]
> > > I just did a test and the upload issue was solved :) but the download still freezing at 5.6k
> > 
> > 
> > Me too it still the same problem for me, Download still doesn't work
> 
> hey, what about your attempts?
The same problem as me, That is still problem for me here, I just upload text file for a short novel but download still shows approximately @ 5.6 K

**Comment by cacs200281** [comment]
Hello,

Just one update...my browser(Chrome and Edge) is showing this mesage at the console:
" The file at 'servername/....' was loaded over an insecure connection. This file should be served over HTTPS.
What it means? Should I have to work only in HTTPS? 
I just want to download a *.txt file from the esp32 to my PC or cellphone :(
Are you experiencing the same issue there @blueokanna ?

**Comment by blueokanna** [comment]
I use chorme and firefox, both shows puase at 5.6K or less(sometimes), No sure what happened there @cacs200281

**Comment by G6EJD** [comment]
It’s because the code is designed around the HTTP protocol rather than HTTPS. 
you could ignore the browser message or change the code for https

**Comment by cacs200281** [comment]
So even if I change the code to HTTPS the problem may not be solved?

**Comment by G6EJD** [comment]
Changing to https will solve the problem, it’s only one line that needs to be changed.

**Comment by cacs200281** [comment]
> Changing to https will solve the problem, it’s only one line that needs to be changed.

I was looking for the solution but all info found is about to use WiFiClientSecure, and change the port...and make a CA certif....etc etc.
Can you help me one more time please?
Thank you.

**Comment by G6EJD** [comment]
You’ve got most of it. 
Chas get the library to the secure version
Yes wificlientsecure and change the port to 440, that’s it, no need for a certificate.

I can’t assist until Saturday or Sunday but it sounds like you have found the answer yourself

**Comment by cacs200281** [comment]
Hey,
I think the port is 443, but It isn't running yet :(
I tried to use some examples from chatgpt but no success yet.
Thanks

**Comment by G6EJD** [comment]
I have attempted to add HTTPS support, but the AsyncWebServer does not support that capability.

You'll need to request the author of the AsyncWebserver adds that requirement.

**Comment by StevenCellist** [comment]
@G6EJD @cacs200281 @blueokanna 
Using https://github.com/G6EJD/G6EJD-ESP-File-Server/issues/1#issuecomment-1356243138 the fix turns out to be very simple..
The problem lies in the lines https://github.com/G6EJD/G6EJD-ESP-File-Server/blob/439a0404cf879bd59cc852aa3370d08d2ab91d18/ESPAsynch_Server_v1.1.ino#L394C33-L394C33 and https://github.com/G6EJD/G6EJD-ESP-File-Server/blob/439a0404cf879bd59cc852aa3370d08d2ab91d18/ESPAsynch_Server_v1.1.ino#L404. Commenting these redirection lines solves the issue.

**Comment by G6EJD** [comment]
OK done that, I haven't had time to test the code yet.

**Comment by cacs200281** [comment]
Hello @StevenCellist !

Just commenting that line solved my problem, thanks a lot!!!
@blueokanna may you will solve your problem too :D 

Thanks one more time Dave!

Cheers

**Comment by blueokanna** [comment]
Congratulations,Actually I am not slove it and I was busy for another project 👍🏼
