### ISSUE TITLE
Ethernet connector

### ISSUE THREAD

**Issue by DanShinde** [G6EJD/G6EJD-ESP-File-Server#7]
Very interesting and efficient server.
But can we try this with an ethernet connector instead of WiFi or with both?

**Comment by G6EJD** [comment]
I've added an Ethernet version, but a lot will depend on your Ethernet board and pin connections to make this work.

**Comment by G6EJD** [comment]
Thanks very much for your efforts it was really appreciated.

**Comment by DanShinde** [comment]
Thank you so much for maintaining this wonderful library actively.
