### ISSUE TITLE
Problem in compiling project for ESP8266 Wemos D1 R1

### ISSUE THREAD

**Issue by Sderenator** [G6EJD/G6EJD-ESP-File-Server#8]
Hello, I'm trying to test this project but I have a lot of errors compiling, due to lack of files...
I tried to use your own libraries without success.
Can you give me any advice?
Thank you!

**Comment by Sderenator** [comment]
![IMG_20240827_153222_998](https://github.com/user-attachments/assets/5757234e-4400-4a6e-904d-f3a1363d75e7)
![IMG_20240827_153223_086](https://github.com/user-attachments/assets/268e1080-9da5-4eee-a56e-f55bf1ddb61b)
![IMG_20240827_153223_743](https://github.com/user-attachments/assets/0c2cc783-ce34-4a48-9c3b-03d65f3f3cdc)

**Comment by G6EJD** [comment]
Downgrade the ESP32 compiler to 1.6.12 or maybe 11 as the newer version has many errors, including the Asynchronous WebServer. 
I have submitted an issue to get it fixed.

**Comment by Sderenator** [comment]
Thank you for your reply.
Do you mean to downgrade the Arduino IDE to 1.6.11?

**Comment by G6EJD** [comment]
You can do both, but when the IDE compiles ESP32 code it uses the boards manager version say 1.0.6

**Comment by Sderenator** [comment]
Sorry, I'm on ESP8266, here the screens of the board manager installed with available versions.
![01](https://github.com/user-attachments/assets/ff1fb881-8cb9-4427-9faf-f6ce3105bd06)
![02](https://github.com/user-attachments/assets/89c88ac8-5891-41fd-829d-f8658339875b)

**Comment by G6EJD** [comment]
I most of the time functions and memory requirements name the ESP8266 unsuitable for this code.
