### ISSUE TITLE
unable to download files other than .txt

### ISSUE THREAD

**Issue by IshaSheikh** [G6EJD/G6EJD-ESP-File-Server#9]
I am working with other files like **.db**. I have faced this issue on other projects too, the library **FS.h** is unable to read the binary of **.db** files while it works seamlessly with .txt files.
To solve this I tried the file handler functions provided by C like the ( **fopen(), fread() etc**) and it worked, but in this this case I tried to modify the code and it didn't work
Heres how I tried:
![image](https://github.com/user-attachments/assets/b0ddcb10-c3ba-4b23-b0b3-2b4dd37a0a4c)
**the commented part is original one**
![image](https://github.com/user-attachments/assets/26996753-d1a3-47ab-9d3d-d5f8a15d3613)
**heres the error**

how do I solve this

**Comment by G6EJD** [comment]
This is a AsynWebServer library error.

**Comment by IshaSheikh** [comment]
it is actually problem with the FS.h library... it does not read .db file at all.
